# version: "3.9"

# services:
#   fastapi_app:
#     build: .
#     container_name: fastapi_app_container
#     ports:
#       - "8000:8000"
#     environment:
#       - PYTHONUNBUFFERED=1
#     restart: always


# version: "3.9"

# services:
#   fastapi_app:
#     build: .
#     container_name: fastapi_app_container
#     ports:
#       - "80:8000"
#     environment:
#       - PYTHONUNBUFFERED=1
#     restart: always


version: "3.9"

services:
  fastapi_app:
    build: .
    container_name: fastapi_app_container
    networks:
      - fastapi_network
    expose:
      - "8000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - fastapi_app
    networks:
      - fastapi_network

networks:
  fastapi_network:
    driver: bridge
