# version: "3.9"

# services:
#   fastapi_app:
#     build: .
#     container_name: fastapi_app_container
#     ports:
#       - "8000:8000"
#     environment:
#       - PYTHONUNBUFFERED=1
#     restart: always


# version: "3.9"

# services:
#   fastapi_app:
#     build: .
#     container_name: fastapi_app_container
#     ports:
#       - "80:8000"
#     environment:
#       - PYTHONUNBUFFERED=1
#     restart: always


version: "3.9"

services:
  fastapi_app:
    build: .
    container_name: fastapi_app_container
    expose:
      - "8000"
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx_container
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - fastapi_app
    restart: always
